# This is the .toml file passed to Locomotion.
# For information on the different settings available, and an example file,
# see the Loconotion README: https://github.com/leoncvlt/loconotion/blob/master/README.md

# DO NOT CHANGE THIS VALUE. The deploy script relies on the site being deployed to the
# "site" directory.
name = "site"

# This page should be the root of your website. It's important.
page = "https://www.notion.so/RavelForGuitar-214bf05bb21280508ba6ea0a49391b79?source=copy_link"

# --- ADD THIS NEW LINE TO SPECIFY THE OUTPUT DIRECTORY ---
output_dir = "dist"
